### ISSUE TITLE
ModuleNotFoundError: No module named 'snakefmt.config'

### ISSUE THREAD

**Issue by tinyheero** [snakemake/snakefmt#101]
Trying to setup `snakefmt` with neovim.  When I installed it using the vim-plug manager using:

```
Plug 'snakemake/snakefmt' 
```

The command produces this message:

```
Error detected while processing function provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 19, in <module>
```

Which suggests it didn't successfully install. When I launch vim, I get this error:

```
Error detected while processing function provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 19, in <module>
ModuleNotFoundError: No module named 'snakefmt.config'
```

Running `:checkhealth  provider` from neovim indicates that Python 3.8.6 is being used and supporting neovim:

```
## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "python3"
  - INFO: Executable: /projects/ace_benchmarking/miniconda3/bin/python3
  - INFO: Python3 version: 3.8.6
  - INFO: python3-neovim version: 0.4.2
  - OK: Latest python3-neovim is installed: 0.3.1
```

I've also got `snakefmt` installed (via conda):

```bash
> which snakefmt
/projects/ace_benchmarking/miniconda3/bin/snakefmt
```

I must be doing something wrong here. The instructions don't explicitly say neovim (https://github.com/snakemake/snakefmt/blob/master/docs/editor_integration.md#Vim). Is the possible that it doesn't work with neovim?

**Comment by bricoletc** [comment]
I'm afraid I don't use neovim, so we would need to find advice from someone who does :thinking:

**Comment by bricoletc** [comment]
Hi @tinyheero , I now use neovim, and successfully installed and ran `snakefmt` inside neovim.
Does this error still occur for you?
If so, could you try installing snakefmt via `pip` not `conda`?
