### ISSUE TITLE
snakemake keywords in 'if' throws an error

### ISSUE THREAD

**Issue by patfiaux** [snakemake/snakefmt#102]
I run snakefmt with the following command:

snakefmt --line-length 99 --diff my_smk.smk > check_smk_diff.txt

and I get the following error:

snakefmt.exceptions.InvalidPython: Got error:
```
Cannot parse: 29:0:         pass
```
while formatting code with black.

The reason is that at line 29 I specify 'configfile'. However, in my case 'configfile' is located in an if statement. Since you mention in your example that "# snakemake keywords are treated like classes i.e. 2 newlines" this gives me an error. If I comment that part out, then snakefmt can proceed without issues.

Example code that gives the error:

# if run directly from snakemake and not wrapper script; get default configuration
if Path(argv[0]).resolve().name == 'snakemake':
    config_loc = Path("path/to/config/file.yml")
    configfile: config_loc  # if I comment this line out all works fine

I would really appreciate it if it were possible to have the above pass the tests without an error! Thanks for the help and the good work!

**Comment by mbhall88** [comment]
Hi @patfiaux, what version of `snakefmt` are you using? When I run that example through the latest version (0.4.0) it formats fine.

`test.smk`
```
if Path(argv[0]).resolve().name == 'snakemake':
    config_loc = Path("path/to/config/file.yml")
    configfile: config_loc  # if I comment this line out all works fine
```

```sh
$ snakefmt -V
snakefmt, version 0.4.0
$ snakefmt - <test.smk
if Path(argv[0]).resolve().name == "snakemake":
    config_loc = Path("path/to/config/file.yml")

    configfile: config_loc  # if I comment this line out all works fine
[INFO] All done 🎉
```

**Comment by patfiaux** [comment]
Hey @mbhall88 , I apologize for not checking that. I assumed that I had installed the 0.4.0 version available on conda but my environment had some conflicts and instead installed 0.1.3 without me noticing. I switched to pip install and that worked like a charm. This issue can be closed on my end.

Thanks for the quick response and helping me solve this!
