### ISSUE TITLE
multiple anonymous rules raise error

### ISSUE THREAD

**Issue by SultanOrazbayev** [snakemake/snakefmt#103]
I'm using `0.4.0` version and it seems that the following code raises an error because of an anonymous rule:

```python
rule all:
    input:
        'a.txt',
        'b.txt',

rule:
    output:
        'a.txt',
    shell:
        """
        echo {output}
        """

rule:
    output:
        'b.txt',
    shell:
        """
        echo {output}
        """
```

The error message is:
> snakefmt.exceptions.DuplicateKeyWordError: L14: 'rule' specified twice.

**Comment by bricoletc** [comment]
Hello, indeed this check has been built-in, but could potentially be removed. Is there any reason not to name your rules?

**Comment by SultanOrazbayev** [comment]
Thank you, I didn't realize this was a feature. For my workflow this is a convenience, since it allows me to avoid repeating myself where the rule name and some of the inputs coincide.

**Comment by mbhall88** [comment]
We probably shouldn't raise an error here as unnamed rules are explicitly allowed by snakemake https://snakemake.readthedocs.io/en/stable/snakefiles/writing_snakefiles.html

**Comment by bricoletc** [comment]
You're right. I made a fix in the dev branch.
