### ISSUE TITLE
Extraneous whitespace after use rule

### ISSUE THREAD

**Issue by Hugovdberg** [snakemake/snakefmt#106]
Every time `snakefmt` is run two new empty lines are inserted after lines containing `use rule`, even when there is already sufficient whitespace.

```
module foo:
    snakefile:
        "rules/foo.smk"

use rule * from foo as foo_*

rule baz:
    output:
        "baz.txt",
    shell:
        "touch {output}"
```

is then converted to (with one empty line to much I believe)

```
module foo:
    snakefile:
        "rules/foo.smk"


use rule * from foo as foo_*



rule baz:
    output:
        "baz.txt",
    shell:
        "touch {output}"
```

and after the next run to

```
module foo:
    snakefile:
        "rules/foo.smk"


use rule * from foo as foo_*





rule baz:
    output:
        "baz.txt",
    shell:
        "touch {output}"
```

And it keeps on growing with each run, which is pretty annoying if you have visual studio code configured to automatically run `snakefmt` on saving.

Version: snakefmt, version 0.4.0

**Comment by bricoletc** [comment]
Thanks for spotting this @Hugovdberg! It is a bug; made a fix in dev branch, and it will be in the next version release.
