### ISSUE TITLE
`snakefmt.exceptions.InvalidParameterSyntax` raised for `resources` directive

### ISSUE THREAD

**Issue by kpj** [snakemake/snakefmt#108]
I am using `snakefmt, version 0.4.1`.

Consider the following Snakefile:
```python
rule foo:
    input:
        "foo",
    output:
        "foo",
    resources:
        time_min=lambda wildcards, attempt: (
            60 * 23 if "cv" in wildcards.method else 60 * 10
        ) * attempt,
```

Executing snakefmt on it results in this error:
```bash
snakefmt.exceptions.InvalidParameterSyntax: 8time_min=lambda wildcards, attempt:(
60*23 if"cv" in wildcards. method else60*10
)* attempt
```

This confuses me as this is a working Snakefile.
Do you have any idea what might be going wrong? Maybe the recently introduced `time_min` parameter from the [LSF profile](https://github.com/Snakemake-Profiles/lsf) is confusing it?

**Comment by bricoletc** [comment]
Sorry for the late reply, looking into this, is most likely a parsing error
