### ISSUE TITLE
snakefmt IndexError: list index out of range

### ISSUE THREAD

**Issue by fgypas** [snakemake/snakefmt#112]
Hi

Thanks for building `snakefmt`. I just tried it with one repo and I have an issue.

More specifically I tried the following:

Install snakefmt via conda:
```
conda create -n snakefmt -c bioconda -c conda-forge snakefmt=0.4.1
```

Activate the virtual environment
```
conda activate snakefmt
```

Clone the dev branch of the following repo and enter the directory
```
git clone -b dev https://git.scicore.unibas.ch/zavolan_group/pipelines/zarp.git
cd zarp
```

Run `snakefmt` as following:
```
snakefmt workflow/
```

Then I get the following message:

> IndexError: list index out of range

 I don't know if I am doing something wrong or if it is a problem of `snakefmt`.

Thank you in advance for your help!

**Comment by bricoletc** [comment]
Hello @fgypas , I cannot reproduce this issue.

One solution that does work for me is the following:

```
python3 -m venv venv
. venv/bin/activate
pip install snakefmt==0.4.1
snakefmt --diff worfklow
```

(though note this actually raises different error- `'NoneType' object has no attribute 'group'`- which occurs when the program processes `workflow/Snakefile`. this bug is fixed in the next coming release of `snakefmt`)

As for conda, I do not get your error when copying your commands, but another one that I'm looking into, relating to an import issue on python 3.6.13.

**Comment by bricoletc** [comment]
@mbhall88 I get following error when runnign the conda commands:

```
Traceback (most recent call last):
  File "/home/brice/miniconda3/envs/snakefmt/bin/snakefmt", line 6, in <module>
    from snakefmt.snakefmt import main
  File "/home/brice/miniconda3/envs/snakefmt/lib/python3.6/site-packages/snakefmt/snakefmt.py", line 9, in <module>
    from black import get_gitignore
  File "/home/brice/miniconda3/envs/snakefmt/lib/python3.6/site-packages/black/__init__.py", line 49, in <module>
    from dataclasses import dataclass, field, replace
ModuleNotFoundError: No module named 'dataclasses'
```
do you know what's up?

**Comment by mbhall88** [comment]
It seems like it might be related to https://github.com/psf/black/issues/1645?

**Comment by fgypas** [comment]
Hi @mbhall88 and @bricoletc 

Thanks for the feedback. I will test again once #113 is merged.

**Comment by fgypas** [comment]
I just tried version 0.4.2 and the error is gone. I am closing the issue. Thanks a lot for the fix.

**Comment by thisIsMikeKane** [comment]
I am having this same issue ('IndexError: list index out of range') on `v0.11.0`.
