### ISSUE TITLE
Syntax Error with `checkpoint rule`

### ISSUE THREAD

**Issue by brcopeland** [snakemake/snakefmt#114]
A minimal example is the following Snakefile:
`checkpoint rule abc:`
Then running `snakefmt` on this:
```
snakefmt Snakefile
SyntaxError: L1: Colon (not 'abc') expected after 'checkpoint rule'
```

**Comment by bricoletc** [comment]
Hi @brcopeland , I believe that statement is syntactically invalid (although `snakemake` may not complain about it). A rule or a checkpoint can either have a single token name or no name, eg `rule a`/`checkpoint a`. if you remove `rule` the error should disappear.

**Comment by brcopeland** [comment]
I see; thank you.  I have been using a `snakemake` pipeline for months with `checkpoint rule` in it seemingly without issue.
