### ISSUE TITLE
egde case: nesting + ruleorder + comment

### ISSUE THREAD

**Issue by siebrenf** [snakemake/snakefmt#126]
Hey guys, I was trying to clean up some code and came upon this super niche edge case. 

Here is the _minimal_ reproducible example. Removing one or both `if`s, removing the bottom comment or replacing the `ruleorder` with anything else does not result in the error.
```python
# when using nested if-statements with___
if True:
    if True:
        ruleorder: ___a_ruleorder_and___

    # ___any comment, breaks the parsing of the next line in snakefmt (v0.4.4)
    var = "anything really"
```

Error message (code ticks replaced with quotes):
```bash
snakefmt.exceptions.InvalidPython: Got error:
'''
Cannot parse: 2:0:     var = "anything really"
'''
while formatting code with black.
```

**Comment by bricoletc** [comment]
Thanks for tracing down the MWE and the specific conditions for failure :)

**Comment by mbhall88** [comment]
@siebrenf would you mind testing out #136 and see if that fixes your issue now? Sorry about the delay, this was hard.
