### ISSUE TITLE
more if-else errors

### ISSUE THREAD

**Issue by siebrenf** [snakemake/snakefmt#128]
Sorry for spamming you with issues. I hope the examples help, and not frustrate :)

This issue seems related to #126, #124 and #115, as it occurs only around nested code. 
In this case, commenting out any of the 4 elements prevents the error. Order is important as well: the error occurs in the 2nd element after the rule. In this example this is `if True`, but you can switch the `def` and the `if` around, and the error would occur in the `def`.

Also note the error is different from the other issues.

Minimal example:
```python
if True:
    rule break_snakefmt_044:
        shell: ""

    def func():
        pass

    if True:
        pass

```

Error:
```bash
  File "<tokenize>", line 4
    if True:
    ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by bricoletc** [comment]
Thanks for reporting all these @siebrenf :) we will work on them though in terms of timing we will be quite slow.

**Comment by mbhall88** [comment]
With v0.6.1 this now gets formatted correctly to

```python
if True:

    rule break_snakefmt_044:
        shell:
            ""


    def func():
        pass


    if True:
        pass
```
