### ISSUE TITLE
Remove dependency to click <8.0.0 ?

### ISSUE THREAD

**Issue by nvuillam** [snakemake/snakefmt#132]
Hi,

I'm the main maintainer of MegaLinter, that embeds lots of linters including your great snakefmt :)

I have a blocking dependency issue with snakefmt as it requires click to be <8.0.0, but I have other linters like black and sqlfluff that requires click >8.0.0

Would it be complicated for you to provide a patch with such dependency removed ?

Thanks & best regards

Note: more info in this issue https://github.com/megalinter/megalinter/issues/1224

**Comment by mbhall88** [comment]
Good timing! I have just created a PR (#133) to update to stable black (and thus v8 of click) to `dev`. This should hopefully be on `master` in the coming days.

**Comment by nvuillam** [comment]
@mbhall88 that's great, thanks a lot :)

**Comment by mbhall88** [comment]
closed with the release of https://github.com/snakemake/snakefmt/releases/tag/0.5.0

**Comment by nvuillam** [comment]
@mbhall88 thank u very much :)
I'll upgrade MegaaLinter so it benefits from your new version :)
