### ISSUE TITLE
Snakefmt fails when config file is missing

### ISSUE THREAD

**Issue by GiulioCentorame** [snakemake/snakefmt#139]
Hi there,
I am using snakefmt as part of super-linter and I noticed the snakefmt run fails whenever it cannot find my configfile:

```
------
WorkflowError in line 3 of /github/workspace/Snakefile:
Workflow defines configfile config.json but it is not present or accessible.
  File "/github/workspace/Snakefile", line 3, in <module>
------
```

This is technically unwanted behaviour for me, as config.json is in my .gitignore (it contains all the system-specific path for my project), is there a way of skipping or getting around this check while running snakefmt?
Thanks!

**Comment by mbhall88** [comment]
I think this is probably coming from `snakemake --lint`, not snakefmt 

https://github.com/snakemake/snakemake/blob/ccddf98521774bb7a6662c3a0b0b8dcf6e8a31de/snakemake/workflow.py#L1280-L1284

**Comment by GiulioCentorame** [comment]
Got it, thanks!
