### ISSUE TITLE
Two empty lines for each include in Snakefile

### ISSUE THREAD

**Issue by alethomas** [snakemake/snakefmt#143]
Since I use the latest version, snakefmt adds two empty lines under each `include:` in the snakefile

**Comment by bricoletc** [comment]
Could you provide a minimal reproducible example? Of a snakefile

**Comment by alethomas** [comment]
Hope that is what you meant:

Before:
<img width="299" alt="Bildschirmfoto 2022-03-08 um 11 29 16" src="https://user-images.githubusercontent.com/77535027/157218738-e9d14803-5cbc-43e6-aa32-eaf6c92fba07.png">


Command:
<img width="519" alt="Bildschirmfoto 2022-03-08 um 11 29 42" src="https://user-images.githubusercontent.com/77535027/157218766-6ccd4d5c-fce4-4ece-bb9b-04613bfd6758.png">

After:
<img width="359" alt="Bildschirmfoto 2022-03-08 um 11 29 59" src="https://user-images.githubusercontent.com/77535027/157218819-b200a4ca-1284-44ca-8514-1c265fb373bc.png">

 @johanneskoester mentioned thats not intended

**Comment by bricoletc** [comment]
Hi @alethomas , thanks for that- i'm a bit surprised as can't reproduce this.

For example:
```sh
python3 -m venv venv
. ./venv/bin/activate
pip install snakefmt
snakefmt --diff - << '@'
include: "rules/common.smk"
include: "rules/benchmarking_common.smk"
include: "rules/utils.smk"
include: "rules/ref.smk"
include: "rules/qc.smk"
@

[INFO] All 1 file(s) would be left unchanged 🎉
```

(Here I gave it a heredoc stdin input, but can also just give it your file)

**Comment by bricoletc** [comment]
If you try those steps, what do you get?

What does 'using VSCode' mean and could that be the source of issue?

**Comment by mbhall88** [comment]
I also can't recreate this using the latest container. 

Closing for now as no response. Feel free to reopen if you're still experiencing trouble @alethomas
