### ISSUE TITLE
Importlib_metadata pinned at very old version

### ISSUE THREAD

**Issue by corneliusroemer** [snakemake/snakefmt#162]
I've noticed that `importlib_metadata` is pinned at version `1.*` when version 2 came out already a 2 years ago

Would it make sense to update this pint or make it less strict?

https://importlib-metadata.readthedocs.io/en/latest/history.html

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/25161793/201155098-196b867c-eb25-4abe-b59e-5830a1eae74d.png">

https://github.com/bioconda/bioconda-recipes/blob/dab3e65f7a3073d0abe3ecf22f249a36b21bfac7/recipes/snakefmt/meta.yaml#L31

https://github.com/snakemake/snakefmt/blob/f136a7ec300310862e501823604f04bffa519c4c/pyproject.toml#L21

**Comment by jbloom** [comment]
I was just having problems with this same point. It is starting to make it hard to install `snakefmt` in pipelines with new versions of other software.

**Comment by bricoletc** [comment]
Will have a look at this in the next 7 days :+1:
