### ISSUE TITLE
Regression in 0.8.0: some comments cause "InvalidPython: Black error:"

### ISSUE THREAD

**Issue by corneliusroemer** [snakemake/snakefmt#169]
Testing new release 0.8.0 I noticed a small regression

```
if config.get("s3_dst"):
    rule one:
        # test
        # test
        output:
            touch("data/one.txt"),
```

Does not format with:

```
InvalidPython: Black error:
Cannot parse: 5:0: <line number missing in source>Snakefmt(snakefmt:black-error:invalid-python)
```

Two comments in a row don't work, maybe this isn't valid snakemake? Not sure.

This is not a big bug, as one can simply put a triple quoted string there instead. Also it's good that it simply fails formatting rather than formatting to something that changes semantics.

cc @mbhall88

**Comment by mbhall88** [comment]
This is valid snakemake. It will be an issue in snakefmt - comments are surprisingly difficult to deal with.

**Comment by ptrebert** [comment]
fwiw, here is another example that triggers that error:

```
rule foo:
    input:
        [],
    run:
        # some comment
        x = 3
```

**Comment by corneliusroemer** [comment]
Ooh, that latter bug is nastier @ptrebert as it's much more likely to be in common use. Did you find that by running 0.8.0 on a standard code base?

**Comment by ptrebert** [comment]
stuff like that is flagged in several of my snakemake files. I would definitely agree that this is quite common (or should be, because we all diligently comment our code, right :wink: )

**Comment by y9c** [comment]
Any double comment lines will cause the error?

```
configfile: "config.yaml"

# AAA
# BBB

BATCH =        "20220202"
```

This one also cause error in version 0.8.

[DEBUG]
snakefmt.exceptions.InvalidPython: Black error:
```
Cannot parse: 4:0:     BATCH = "20220202"

(Note reported line number may be incorrect, as snakefmt could not determine the true line number)
```

**Comment by corneliusroemer** [comment]
Another example of probably the same bug:
```
onstart:
    # Saves onstart Slack message thread timestamp to file SLACK_TS_FILE
    shell(
        f"./bin/notify-on-start {config.get('build_name', 'unknown')} {SLACK_TS_FILE}"
    )
```

Workaround is to use docstring `""" comment """`

**Comment by mbhall88** [comment]
Thanks, I'm currently working on this issue, hopefully will have something in the next day or two
