### ISSUE TITLE
ENH: Make `--comapct-diff` truly compact

### ISSUE THREAD

**Issue by corneliusroemer** [snakemake/snakefmt#175]
We're using snakefmt in CI for the monkeypox Nextstrain build: https://github.com/nextstrain/monkeypox/blob/0ffc8d8451a4250aea95a9240551401575c0f6e6/.github/workflows/ci.yaml#L18

Snakefmt failed after version update from 0.8.0 to 0.8.1 but since we use `--check` it wasn't immediately obvious what the differences were.

This prompted me to see whether it's possible to improve output.

`snakefmt --check .` by itself just produces the following:

```console
[INFO] 2 file(s) would be changed 😬
[INFO] 10 file(s) would be left unchanged 🎉
```

One option would be to add a list of files that would be changed to the `snakefmt --check .` output.

I tried out the two diff options `--diff` and `--compact-diff` to see if an existing option helps here.

`--diff` is definitely too verbose for this CI usecase. But to my surprise, so is `--compact-diff`.

I was surprised that `--compact-diff` includes the following 3 lines even for unchanged files:

```console
=====> Diff for workflow/snakemake_rules/core.smk <=====


```

This makes a lot of noise. It would be nice if there was a `--very-compact-diff` option that only showed diffs for files to be changed. Or if `--compact-diff` was changed to not output files with no-ops.

**Comment by mbhall88** [comment]
You can use the `--verbose/-v` option to list the files that would be changed with the `--check` option. Here is an example

```
[DEBUG] Included: workflow/rules/metadata.smk matched the --include regular expression
[DEBUG] Ignoring: workflow/envs/metadata.yaml did not match the --include regular expression
[DEBUG] Included: workflow/Snakefile matched the --include regular expression
[DEBUG] Ignoring: workflow/scripts/submit_slurm.sh did not match the --include regular expression
[DEBUG] Ignoring: workflow/scripts/get_metadata.py did not match the --include regular expression
[DEBUG] Ignoring: workflow/scripts/combine_metadata.py did not match the --include regular expression
[DEBUG]
[DEBUG] In file "workflow/Snakefile":  Formatted content is different from original
[DEBUG]
[INFO] 1 file(s) would be changed 😬
[INFO] 1 file(s) would be left unchanged 🎉
```

I agree that only outputting the files to be changed in the compact diff and diff is probably a much better option
