### ISSUE TITLE
Feature request: Add CITATION.cff

### ISSUE THREAD

**Issue by schackartk** [snakemake/snakefmt#194]
Thank you for this tool, it is very useful!

**Issue description**
I am unsure of how to properly cite snakefmt in a research article.

**Describe the solution you'd like**
I would like to see a CITATION.cff file in the root of the repository.

[GitHub recommends](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files), and integrates support for, [CITATION.cff](https://citation-file-format.github.io/) files. Inclusion of this file would immediately have these benefits:

- Users will have the necessary metadata to properly cite snakefmt.
- GitHub can automatically generate both APA and BibTeX formatted citations. A "Cite this repository" option will automatically appear on the repo's sidebar when viewed on a desktop browser.
- Reference managers like Zotero will automatically detect the metadata so the user can save the citation to their library.

**Additional context**
Examples of popular packages using this are [pandas](https://github.com/pandas-dev/pandas) and [tensorflow](https://github.com/tensorflow/tensorflow).

I would be happy to create an initial version of this and open a PR if there is interest in possibly merging it after refinement.

**Comment by mbhall88** [comment]
Hi @schackartk, you can simply cite the [snakemake paper](https://snakemake.readthedocs.io/en/stable/#citation).

I'll add a citation file today

**Comment by schackartk** [comment]
I do think it's helpful to have another citation for snakefmt itself in addition to the Snakemake paper in case users are interested, so I'm glad to see it will be implemented!

**Comment by mbhall88** [comment]
Well snakefmt is explicitly described in section 2.2.2 of the paper, so citing snakemake is definitely the best option.
