### ISSUE TITLE
Prevent newline for shell triple-quote

### ISSUE THREAD

**Issue by alpha-beta-soup** [snakemake/snakefmt#201]
```
  rule archive:
+     input:
-     input: FOOTPRINT
?     ^^^^^^
+         FOOTPRINT,
?     ^^^          +
-     output: ARCHIVE
?            --------
+     output:
+         ARCHIVE,
-     shell: '''
?           ----
+     shell:
+         """
          mkdir -p $(dirname {output})
          zip -r {output} './data'
-     '''
+     """
```

That is, 

```
shell: '''
    some-command {output} {input}
'''
```

Is formatted to:

```
shell:
    """
    some-command {output} {input}
"""
```

However the newline loses the syntax highlighting in VS Code, at least with my current settings:

Before:
![Screenshot from 2023-09-18 11-40-28](https://github.com/snakemake/snakefmt/assets/5925045/fd4c54f1-d991-49b7-b91e-c30afa718239)

After:
![Screenshot from 2023-09-18 11-40-47](https://github.com/snakemake/snakefmt/assets/5925045/7a2f573d-95ca-4634-8376-87c4ea51b27e)

I'd be interested in either learning how to disable that change, or perhaps just knowing what I could tweak in VS Code to continue to see `{output}` etc with string-format syntax-highlighting, as this is really quite useful for more complex rules.

**Comment by mbhall88** [comment]
You can't disable this change from snakefmt. I suspect your issue may have something to do with VS Code? But I can't help you there as I don't use VS Code sorry. I'll leave this open and hopefully someone else who uses it can shed some light....

**Comment by hermidalc** [comment]
The syntax highlighting is lost even with single line shell commands if you put a newline before the command string

**Comment by mbhall88** [comment]
Just to reiterate, snakefmt is doing the right thing here - I suspect the issue is with the VS Code plugin

**Comment by alpha-beta-soup** [comment]
What makes this the "right thing"? Is it a Black thing? I actually prefer the output without an additional line break, _particularly_ in the case of single line command strings. But I appreciate offloading the concern and I agree that there's an issue with the Snakemake syntax highlighting in VS Code more than snakefmt.

The relevant issue seems to be https://github.com/snakemake/snakemake-lang-vscode-plugin/issues/7

**Comment by mbhall88** [comment]
> What makes this the "right thing"? Is it a Black thing? I actually prefer the output without an additional line break, particularly in the case of single line command strings.

This was the convention we settled on with Johannes. All directives, expect (I think) `threads`, will have a newline and then their arguments
