### ISSUE TITLE
Bug: snakefmt erroneously removes double braces, {{x}} -> {x} 

### ISSUE THREAD

**Issue by corneliusroemer** [snakemake/snakefmt#207]
Snakefmt makes illegal syntax changes:

```
rule align:
    input:
        sequences="results/{build_name}/filtered.fasta",
    params:
        translation_template=lambda w: f"results/{w.build_name}/translations/{{cds}}.fasta",
```

is formatted to

```
rule align:
    input:
        sequences="results/{build_name}/filtered.fasta",
    params:
        translation_template=lambda w: f"results/{w.build_name}/translations/{cds}.fasta",
```

I.e. the double curly braces around `{{cds}}` are replaced by single curly braces `{cds}`.

This might be ok to do in Python, but it isn't ok in Snakemake, as I need literal braces here, no replacement at all is wanted.

<img width="2058" alt="image" src="https://github.com/snakemake/snakefmt/assets/25161793/886d1e5b-8ab8-4170-973f-f884ccff31de">

This happens with the snakefmt in precommit:   rev: v0.8.4

**Comment by mbhall88** [comment]
Ooof that's not good. Sorry it's been hard to find time to work on this tool in recent months.  
I will try and look into these bugs in the coming month or two, but feel free to have a look too. We'd be very happy to have the community involved

**Comment by corneliusroemer** [comment]
No worries at all, I understand it's hard to maintain snakefmt.

This bug is really weird, the fact it's only affecting pre-commit could mean something is wrong in that part, or maybe not even within snakefmt. I'll see if I can investigate further, this seems hard to repro for others, I think.

**Comment by mbhall88** [comment]
@corneliusroemer I can't replicate this error in snakefmt 0.8.5. Can you confirm your precommit is definitely using 0.8.5?

**Comment by corneliusroemer** [comment]
I'm trying to set up a minimal reproducible example but getting some weird pre-commit installed errors like:
```log
 note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for multidict
    ERROR: Could not build wheels for multidict, which is required to install pyproject.toml-based projects
```

Will have a look later and try again when I have more time.

**Comment by y9c** [comment]
Might relative to Python version? Can reproduce under Python 3.12

**Comment by corneliusroemer** [comment]
Great catch @y9c!
