### ISSUE TITLE
if-else expression under python3.12 cannot be formatted

### ISSUE THREAD

**Issue by y9c** [snakemake/snakefmt#210]
Input file:

```python
a = f"{1 + 2}"  if 1 > 0 else   f"{1 - 2}"
```

Error:

snakefmt.exceptions.InvalidPython: Black error:
```
Cannot parse: 1:22: a =f"{1 + 2}"if 1 > 0 elsef"{1 - 2}"

(Note reported line number may be incorrect, as snakefmt could not determine the true line number)
```

---

version information:

- snakefmt, version 0.8.5
- black, 23.12.1 (compiled: yes)
- Python 3.12.0

**Comment by mbhall88** [comment]
Just confirming I can reproduce this. Seems to only fail on python 3.12 for some weird reason.
