### ISSUE TITLE
Indentation and whitespace

### ISSUE THREAD

**Issue by johanneskoester** [snakemake/snakefmt#22]
It is recommended to follow pep8 defaults when formatting snakemake.
That means:

* indent with 4 spaces
* no whitespace around `=` for keyword arguments, and similarly around any named input, output, params etc. items.

**Comment by bricoletc** [comment]
This is now enforced :-)

**Comment by johanneskoester** [comment]
Also, always have a newline after each "keyword:" within a rule, except if there is just a numeric. So, e.g.
```
    shell:
         "echo test > {output}"
```

But 
```
    threads: 8
```

Bonus: when having shell commands that are longer than 80 chars, split them up into multiple lines like this

```
    shell:
        "some --command --that --is --very --long "
        "-- with --a --lot --of --args {output}"
```

**Comment by bricoletc** [comment]
Your first point is addressed!

For the bonus of shell formatting, do you propose also combining short lines? This to me makes less sense for eg:

```
shell:
    "for i in $(seq 1 3);
    "do echo $i;"
    "done"
```

Should stay as is

**Comment by mbhall88** [comment]
Hmmm, the string splitting thing is quite hard I think. I'm pretty sure black doesn't even handle this?

**Comment by mbhall88** [comment]
Im going to close this issue as I believe the issues (except shell string splitting) are all addressed. If there are other specific problems, best to raise them in individual issues.
