### ISSUE TITLE
Addition of unwanted whitespaces when a function is called within an expression section of an f-string

### ISSUE THREAD

**Issue by enixmail** [snakemake/snakefmt#220]
When a function is called within an expression section of an f-string, `snakefmt` will add unwanted whitespaces around the equal (=) sign when assigning a value to a named parameter and will also add a whitespace before a comma separating the parameters in that function call.

Example code:
```python
import json


job_properties = {"resources": {"mem": "1GB"}}

test = f"job_properties: {json.dumps(job_properties, indent=4)}"
```

running snakefmt --diff will result in the following:
```shell
> snakefmt --diff test_add_unwanted_whitespaces.py 
=====> Diff for test_add_unwanted_whitespaces.py <=====

  import json
  
  
  job_properties = {"resources": {"mem": "1GB"}}
  
- test = f"job_properties: {json.dumps(job_properties, indent=4)}"
+ test = f"job_properties: {json.dumps(job_properties , indent = 4)}"
?                                                    +        + +
```

Note this was with `snakefmt` 0.10.0 installed through `conda`, and the version of black that comes with it sees no problem with that file:
```shell
> black --diff test_add_unwanted_whitespaces.py
All done! ✨ 🍰 ✨
1 file would be left unchanged.
```

**Comment by mbhall88** [comment]
Thought that might be the case. We've had some issues trying to deal with how the tokenizer now presents us with f-strings.

I'll try and get around to this soon

**Comment by bricoletc** [comment]
I'll have a go at this soon
