### ISSUE TITLE
Spurious additional space added between adjacent replacement fields

### ISSUE THREAD

**Issue by edbennett** [snakemake/snakefmt#222]
This is almost certainly closely related to #220, but when an `f`-string contains two adjacent replacement fields (e.g. `f"{var1}{var2}"`) then `snakefmt` will insert a space between them (i.e. `f"{var1} {var2}"`).

Since in general filenames are sensitive to having extra characters inserted, this means that a working rule is broken by this change.

This occurs with Python 3.12 but not Python 3.11.

**Comment by mbhall88** [comment]
Urgh that is quite nasty. I'll try and get to around to this ASAP

**Comment by mbhall88** [comment]
@edbennett I can't seem to reproduce this with the latest snakefmt. Can you confirm you're using v0.10.0 and if so, can you provide an example that reproduces the behaviour?

**Comment by edbennett** [comment]
Thanks! To confirm, #223 correctly fixes the errant behaviour in the case that was causing me issues.
