### ISSUE TITLE
Specifying conda directive within Snakefile (and even before imports) should be supported

### ISSUE THREAD

**Issue by hermidalc** [snakemake/snakefmt#243]
With Snakemake you can now specify the `conda` directive in your Snakefile even before imports to specify global workflow dependencies and environment. https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#global-workflow-dependencies

When I define this directive snakefmt thinks it's an error:

```
InvalidPython: Black error:
Cannot parse: 7:6: conda:
```

**Comment by mbhall88** [comment]
This is a duplicate of #209  

Global use of `conda:` was added in v8.0, so will have to wait until we support v8.
