### ISSUE TITLE
Which keywords can occur more than once?

### ISSUE THREAD

**Issue by bricoletc** [snakemake/snakefmt#27]
Right now, `snakefmt` allows the following to occur more than once:

* include
* ruleorder
* localrules

`snakemake` allows quite a few more, including `configfile`, `workdir`, `container`, `report`.

(Actually I can see `configfile` multicopy should be supported, the config dictionary gets updated for every new file.)

Which keywords can be multicopy?
Might be worth updating the [grammar](https://snakemake.readthedocs.io/en/stable/snakefiles/writing_snakefiles.html#grammar) to reflect this

**Comment by bricoletc** [comment]
`configfile` can now occur >1

**Comment by johanneskoester** [comment]
For container and report, there is no need to occur more than once, except overwriting them in different included files.
Does your parser error out if that happens?

**Comment by bricoletc** [comment]
For current tip of master, anything other than in `{"include", "ruleorder", "localrules", "configfile"}` does indeed error out. Do you think all top-level duplicated keywords should not cause error?

**Comment by johanneskoester** [comment]
Yes, sounds good to me. I don't think snakefmt should try to do the job of a linter or snakemake itself here. Just formatting.

**Comment by bricoletc** [comment]
Yet, in order to format properly, it needs a parser that's aware of the grammar. So its an easy bonus to validate the grammar. I think it could be valuable to formalise which keywords can occur twice. But for now i can just disable this !

**Comment by bricoletc** [comment]
From bb1543e parameter keywords in duplicate (eg `configfile`, `include`, `input`, `output`) do not cause parsing errors. It's fairly easy to roll that back in should it be needed.

rule named in duplicate do cause parsing errors, as does snakemake currently.
