### ISSUE TITLE
Option to indent the shell section

### ISSUE THREAD

**Issue by enixmail** [snakemake/snakefmt#39]
This is just a suggestion, for when you'll be at the point to insert "nice to have" items.

I saw your discussion about not indenting the inside of multi-lines string shell sections
https://github.com/snakemake/snakefmt/pull/35#issuecomment-619265482
and while I understand your point of view, I was also very disappointed as I was counting on that feature.

For an obscure reason, when I started building Snakemake workflows, I used a 2 spaces indentation instead of 4, so I have several Snakefiles following this pattern:
```
rule rule1:
  output:
    "output.txt"
  shell:
    """
    echo Hello
    touch {output[0]}
    """
```
which I was hoping `snakefmt` would fix (the indentation) this way:
```
rule rule1:
    output:
        "output.txt",
    shell:
        """
        echo Hello
        touch {output[0]}
        """
```
It could be nice to have a command line argument like `--force-shell-indent` to have `snakefmt` also adjust the indentation of the lines inside the multi-lines string shell sections.

Thanks!

**Comment by johanneskoester** [comment]
I agree, it definitely should be indented this way.  And this should be the default. Otherwise, it seriously hampers readability. I think this should be doable using textwrap from the standard library.

**Comment by johanneskoester** [comment]
cc @mbhall88 @bricoletc

**Comment by johanneskoester** [comment]
I think this should work:
```
textwrap.indent(textwrap.dedent(shellcmd.split()), " " * shell_indentation_level)
```

**Comment by bricoletc** [comment]
Hey @enixmail , I think this is fixed with 0499a7f, you get your two spaces reindented properly!

Note I reindent by the lowest indented element, and then relative indenting is maintained so on:

```
rule rule1:
  shell:
    """
 echo Hello
    touch {output[0]}
    echo World
"""
```

(Hard to see, but a single space before `echo Hello`)
The output is

```
rule rule1:
    shell:
        """
        echo Hello
           touch {output[0]}
           echo World
        """
```

**Comment by enixmail** [comment]
With commit 0499a7f, the shell sections are now well indented, but I think that docstrings might have been affected.

Using this Snakefile:
```
def foo():
  """This is a Python function docstring summary line

  Here is the description portion of
  the docstring.
  """
  print("Hello")


rule all:
  """This is a rule docstring summary line

  Here is the description portion of
  the docstring.
  """
  output:
    "output.txt",
  shell:
    """
    echo Hello
    touch {output[0]}
    """
```

I expect to get that as output from `snakefmt`:
```
def foo():
    """This is a Python function docstring summary line

    Here is the description portion of
    the docstring.
    """
    print("Hello")


rule all:
    """This is a rule docstring summary line

    Here is the description portion of
    the docstring.
    """
    output:
        "output.txt",
    shell:
        """
        echo Hello
        touch {output[0]}
        """
```

but currently the output is this:
```
def foo():
    """This is a Python function docstring summary line

  Here is the description portion of
  the docstring.
"""
    print("Hello")


rule all:
    """This is a rule docstring summary line

      Here is the description portion of
      the docstring.
    """
    output:
        "output.txt",
    shell:
        """
        echo Hello
        touch {output[0]}
        """
```

**Comment by bricoletc** [comment]
Hey @enixmail , thanks for the follow-up. I've made a fix relating to python code but don't think we should be reindenting your docstring.

If you run `black` on :

```
def foo():
  """This is a Python function docstring summary line

  Here is the description portion of
  the docstring.
  """
  print("Hello")
```

You get:
```
def foo():
    """This is a Python function docstring summary line

  Here is the description portion of
  the docstring.
  """
    print("Hello")
```

Which is what i've implemented with a coming commit. 
Under shell I agree we should reformat triple quoted strings for readability, but i think we should generally maintain that triple quoted strings get left as the coder wrote them.

Open to discussion of course

**Comment by bricoletc** [comment]
Another option is to reformat all triple quoted strings and not do it as black there.

**Comment by enixmail** [comment]
I misread [PEP 257](https://www.python.org/dev/peps/pep-0257/) and was under the (false) impression that the text of all the other lines within the multi-lines docstring had to be left aligned with the start of the opening triple double quotes, which is not the case. Looking at Black's issues list, docstrings seem to have fueled many discussions, I guess `snakefmt` should simply stick to what `black` is doing with docstrings.
Thanks!

**Comment by bricoletc** [comment]
Sure!
