### ISSUE TITLE
Wrong indentation for multi-line if statement at file level

### ISSUE THREAD

**Issue by enixmail** [snakemake/snakefmt#40]
When having a multi-lines if statement at file level, the second and following lines are not indented.

Note: this was ran from commit 9919e4b

Given this Snakefile:
```
if (config['a'] is None and
    config['b'] is None and
    config['c'] is None):


    rule rule1:
        output:
            "my_input_1.txt",
        shell:
            "touch {output[0]}"


elif (config['d'] is None and
      config['e'] is None):


    rule rule2:
        output:
            "my_input_2.txt",
        shell:
            "touch {output[0]}"


else:


    rule rule3:
        output:
            "my_input_3.txt",
        shell:
            "touch {output[0]}"
```

`snakefmt` formats it this way:
```
if (config['a'] is None and
config['b'] is None and
config['c'] is None):


    rule rule1:
        output:
            "my_input_1.txt",
        shell:
            "touch {output[0]}"
elif (config['d'] is None and
config['e'] is None):


    rule rule2:
        output:
            "my_input_2.txt",
        shell:
            "touch {output[0]}"
else:


    rule rule3:
        output:
            "my_input_3.txt",
        shell:
            "touch {output[0]}"
```

Also, to be discussed in #38 I guess, blank lines are removed between the end of the rule and the `elif` or `else` keywords (should it be 2 blank lines as a top element or simply because of the `rules` inside?).

**Comment by bricoletc** [comment]
Gah. I'm struggling to think what is readable here. Should we have 2 lines between the python code and the nested `rule`, and two lines before `rule` and python code @johanneskoester ?

**Comment by bricoletc** [comment]
Also, thanks @enixmail for spotting ;-)

**Comment by bricoletc** [comment]
`black` does this:

```
if p:

    def p():
        pass


elif p2:

    def p2():
        pass


else:

    def p3():
        pass
```

One line before the function, two lines after

**Comment by mbhall88** [comment]
I think using black as a guide is a safe bet.

**Comment by bricoletc** [comment]
Alrighty with the latest commits (on `dev`, will PR to master) here is the diff with your file @enixmail 

```
+ if config["a"] is None and config["b"] is None and config["c"] is None:
- if (config['a'] is None and
-     config['b'] is None and
-     config['c'] is None):
- 
  
      rule rule1:
          output:
              "my_input_1.txt",
          shell:
              "touch {output[0]}"
  
  
+ elif config["d"] is None and config["e"] is None:
- elif (config['d'] is None and
-       config['e'] is None):
- 
  
      rule rule2:
          output:
              "my_input_2.txt",
          shell:
              "touch {output[0]}"
  
  
  else:
  
- 
      rule rule3:
          output:
              "my_input_3.txt",
          shell:
              "touch {output[0]}"
```
So implemented the black-like one line spacing in indented context, two line spacing at top leve.

Also the first if condition gets formatted, this is now generic to all python statements preceding snakemake code in nested contexts.

Note for your specific example the line is short enough to get collapsed, but make it longer and you get

```
if (
    config["a"] is None
    and config["b"] is None
    and config["d"] is None
    and config["c"] is None
):
```

So looking dandy!

I will close if you're happy with this.
