### ISSUE TITLE
Dot operator not recognized within if statement at file level

### ISSUE THREAD

**Issue by enixmail** [snakemake/snakefmt#41]
When using a dot operator within an `if` statement at file level, it is not recognized as such by `snakefmt`.

Note: this was ran from commit 9919e4b

Given this Snakefile:
```
if (not config["a"] is None and config["a"].strip() != ""):


    rule rule1:
        output:
            config["a"].upper(),
        shell:
            "touch {output[0]}"


else:


    rule rule2:
        output:
            "my_input_2.txt",
        shell:
            "touch {output[0]}"
```

`snakefmt` formats it this way:
```
if (not config["a"] is None and config["a"] . strip () != ""):


    rule rule1:
        output:
            config["a"].upper(),
        shell:
            "touch {output[0]}"
else:


    rule rule2:
        output:
            "my_input_2.txt",
        shell:
            "touch {output[0]}"
```
See how `config["a"].strip()` becomes `config["a"] . strip ()` within the `if` statement.

**Comment by bricoletc** [comment]
while the `.` operator is now dealt with (thanks for the spot!), this issue touches on a deeper point which is `black` not being run on certain chunks of code which are followed by snakemake syntax. so keeping this open as a work in progress.

**Comment by bricoletc** [comment]
As stated in #40 , the problem of `black not being run on certain chunks of code` is now largely solved.
