### ISSUE TITLE
Unit test template and convention

### ISSUE THREAD

**Issue by mbhall88** [snakemake/snakefmt#42]
I think it would be a good idea to decide on a unit testing convention as we have been changing each other's unit tests to satisfy our own internal standards. Some good blogs outlining different conventions can be found:
- https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices
- https://thecodebuzz.com/tdd-unit-testing-naming-conventions-and-standards/
- https://dzone.com/articles/7-popular-unit-test-naming

@bricoletc are you happy to decide on a standard or would you prefer to just keep doing things as we are?

**Comment by bricoletc** [comment]
I guess a few standards that matter:

* lowercase test functions?
* make tests as short as possible. this include using small text strings if possible, and using `expect` and `actual` variables when they aren't very small (eg if `expect` is a one word string or an int, just use that directly)
* many test classes with few test functions rather than the opposite

**Comment by mbhall88** [comment]
> I guess a few standards that matter:
> 
>     * lowercase test functions?
So do we want something like
1. `test_invalid_string_raises_error`
2. `test_invalidString_raisesError`

I used to use option 2 (Robyn's suggested pattern), but for some weird reason, I have started doing 1 recently :shrug:. If I had to pick one, I like option 2, but that's a very marginal preference so I don't mind which one we use. Whichever you prefer (if you have a preference).
> 
>     * make tests as short as possible. this include using small text strings if possible, and using `expect` and `actual` variables when they aren't very small (eg if `expect` is a one word string or an int, just use that directly)

Sounds good. I quite like the [Given-When-Then](http://www.draconianoverlord.com/2017/11/28/given-when-then.html) pattern.
> 
>     * many test classes with few test functions rather than the opposite

Agreed. I like having a class for each function being tested.

**Comment by bricoletc** [comment]
I'd say let's do lowercase only when possible and Robyn's pattern when that becomes too long then

**Comment by mbhall88** [comment]
Ok, so just for clarity, here is a **suggested** example template

```py
class TestMyFunction:
    def test_case_being_tested_expected_result(self):
        # Given
        foo = ObjectSetup()

        # When
        actual = foo.my_function()
        expected = "foo"

        # Then
        assert actual == expected
```

One reason for checking the two variables are equal rather than inline evaluating is that when stepping through with the debugger it becomes much easier to see what is happening in the evaluation of both actual and expected.  

Sometimes it also makes sense to skip the `When` part. For example, if testing a function called `is_unmapped`, it is far more readable to just say `assert foo.is_unmapped()`.

Feel free to suggest changes.

**Comment by bricoletc** [comment]
Sounds alright to me as a template, but I am a little keen to skip using actual/expected when they are very short. Only so as to cut down on the several 100's of lines of tests we have.
