### ISSUE TITLE
Not writing changes anymore

### ISSUE THREAD

**Issue by johanneskoester** [snakemake/snakefmt#44]
I just tested the latest master commit, and it seems that it does not write changes to disk anymore? Everything is just printed to STDOUT. Is that change intentional?

**Comment by mbhall88** [comment]
It seems to be writing to file for me... What command are you running?

Also confirming you've updated your git remote to `snakemake/snakefmt` and it isn't on my old one? And the commit is 58c4ebaa02ebfcb384a2b02c4eafb116e3362e45?

**Comment by johanneskoester** [comment]
You are right, my fault! I indeed had the wrong remote. Sorry for the noise.
