### ISSUE TITLE
Release and bioconda package?

### ISSUE THREAD

**Issue by johanneskoester** [snakemake/snakefmt#45]
Hi guys,
the results look pretty good. I think it might be time for the first release and a bioconda package?

Best,
Johannes

**Comment by bricoletc** [comment]
Good news!
One thing we wondered about is if it makes sense to distribute `snakefmt` with snakemake somehow? For eg bundling it inside the snakemake build package.

**Comment by johanneskoester** [comment]
That is indeed not a bad idea. How would that work technically? With a git submodule?

**Comment by mbhall88** [comment]
I would personally prefer them to be separate, but if you both would prefer them together that's fine by me. Although, I have no idea how you would distribute it with `snakemake`... I guess it might also be extra complicated given we are using different build systems.

**Comment by bricoletc** [comment]
Would it not be enough to package `snakefmt` on PyPi and add it to install_requires or extras_require in snakemake's `setup.py`?

One caveat is `snakefmt` currently depends on snakemake but only for testing purposes- to check the snakemake syntax is being correctly tracked. We could make that a dev dependency only so as to avoid that dependency at install time.

**Comment by mbhall88** [comment]
Yeah, both of those suggestions seem good to me.

**Comment by bricoletc** [comment]
OK, here is a proposal:
- I've just made `snakemake` a dev dependency for `snakefmt`. This is because we have unit tests which check that the keywords recognised by snakefmt are the same as latest snakemake.
- This means `snakemake` shouldn't put `snakefmt` as an `install_requires` depedency. Otherwise when installing snakefmt for development, we will have a circular dependency: snakefmt->snakemake->snakefmt. 
Instead we could add `snakefmt` to `extras_require`, for eg as 
```
    extras_require={
        "reports": ["jinja2", "networkx", "pygments", "pygraphviz"],
       ...
        "formatting": ["snakefmt"]
    },
```

Then one way to install snakemake with snakefmt is `pip install snakemake[formatting]`. 
There might be a way to add a flag to snakemake like `--format`, like for `--report`, which would install snakefmt as a dynamic dependency? Current snakemake has these extras for reporting.

**Comment by johanneskoester** [comment]
Mhm, I think we don't actually need it as a dependency of snakemake itself. It can just stay separate. On conda, where we have snakemake and snakemake-minimal, it can be a dependency of snakemake, which anyway pulls in all kinds of goodies.

**Comment by mbhall88** [comment]
Hi @johanneskoester , @bricoletc and I agree that everything is all ready to go for the first release.

The last thing we need is for you to create a pypi API token and add a secret for the password to this repo so the github action can create pypi releases when we push a release tag. Instructions on how to create the token and add the password secret are at <https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#saving-credentials-on-github> (don't worry about the test-pypi stuff).

Additionally, could you also create a snakefmt dockerhub project under the snakemake org and add [secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets) to the github repo for the username and password?

I have setup a [release workflow](https://github.com/snakemake/snakefmt/blob/master/.github/workflows/release.yaml) that will handle all these deploys (provided the secrets are added).

**Comment by johanneskoester** [comment]
Pypi token is there, under secrets.PYPI_TOKEN.

**Comment by johanneskoester** [comment]
Regarding docker, do you want a separate container image for snakefmt?

**Comment by johanneskoester** [comment]
Never mind, understood and created. Secrets are secrets.DOCKER_USERNAME and secrets.DOCKER_TOKEN.

**Comment by mbhall88** [comment]
We're live https://github.com/snakemake/snakefmt/commit/ad48be0a4d93d0fb042093c79d964a4976173272!

- [x] PyPi => <https://pypi.org/project/snakefmt/>
- [x] DockerHub => <https://hub.docker.com/r/snakemake/snakefmt>
- [ ] Bioconda => <https://github.com/bioconda/bioconda-recipes/pull/22890>
- [ ] Homebrew
