### ISSUE TITLE
Indenting in rule docstrings

### ISSUE THREAD

**Issue by mbhall88** [snakemake/snakefmt#51]
`test.smk`
```
rule all:
    """multi line
    docstring
    """
    input: "data/results.txt"
```

```
$ snakefmt - < test.smk
rule all:
    """multi line
        docstring
        """
    input:
        "data/results.txt",
[INFO] All done 🎉
```

It seems the indenting inside the docstring is slightly off.

Looking at `black`s behaviour in a similar situation, it doesn't touch docstrings at all. Maybe we should also take the same approach?

**Comment by bricoletc** [comment]
Great spot.

I think we've been through this discussion, in #39 . What came out there was that something like
```
shell:
"""Hello
    World
        World
"""
```
should go to

```
shell:
    """Hello
    World
        World
    """
So we reindent, and preserve relative indents (here between the two `World`).

I've added a fix to the bug you found!
