### ISSUE TITLE
f-strings with triple quoted strings break

### ISSUE THREAD

**Issue by siebrenf** [snakemake/snakefmt#55]
Couldn't wait to use this! 

Conda install, version 0.1.0

Triple quoted f-strings seem to break in rules, both when using `run` and `shell`.
Below are two minimal examples. Adding braces to the string does not alter the behavior.

`run` before:
```
rule test:
    run:
        shell(f"""shell stuff""")
```

`run` after:
```
rule test:
    run:
        shell(f        """shell stuff"""        )
```

`shell` before:
```
rule someshellrule:
    shell:
        f"""shell stuff"""
```

`shell` after:
```
rule somerunrule:
    shell:
        f        """shell stuff"""
```

**Comment by bricoletc** [comment]
Thanks for spotting this @siebrenf ! 
It's clearly a bug and fixed in d7bab0d.
