### ISSUE TITLE
Problem with multi-line script strings

### ISSUE THREAD

**Issue by holtgrewe** [snakemake/snakefmt#59]
```
rule top:
    shell:
        r"""
        Multi_line
        """
```

becomes

```
rule top:
    shell:
        r"""
                Multi_line
                """
```

becomes

```
rule top:
    shell:
        r"""
                        Multi_line
                        """
```

etc.

**Comment by mbhall88** [comment]
Hi @holtgrewe 

Can I ask why you are using an r-string? If you remove the `r` `snakefmt` produces the desired output.

**Comment by holtgrewe** [comment]
@mbhall88 thanks for the info. I'm using the string as I'm regularly using `\` in my shell scripts :D

**Comment by mbhall88** [comment]
Ah yes, I figured that might be the case. Ok, we will work on implementing a fix for this and let you know.

**Comment by mbhall88** [comment]
@holtgrewe could you try out the tip of `dev` and make sure it fixes issue for you?

**Comment by bricoletc** [comment]
> @holtgrewe could you try out the tip of `dev` and make sure it fixes issue for you?

@mbhall88  I think we can close and let @holtgrewe or anyone else comment here if relevant?
