### ISSUE TITLE
Vim plugin

### ISSUE THREAD

**Issue by bricoletc** [snakemake/snakefmt#62]
As part of adding editor integration, could make a vim plugin as in [black](https://github.com/psf/black/blob/master/plugin/black.vim)

**Comment by ashwinvis** [comment]
Perhaps configuring in some popular plugin would do? For example:
- https://github.com/sbdchd/neoformat
- https://github.com/chiel92/vim-autoformat

**Comment by bricoletc** [comment]
@ashwinvis there is now a self-contained vim plugin: https://github.com/snakemake/snakefmt/blob/master/docs/editor_integration.md#vim.

However, it could be interesting to add support for `vim-autoformat` in the future. I guess one option is just writing up a section in the editor_integration document saying i)Set up filetype detection ii)Setup `formatters` and `formatdef` for the `snakemake` file type as per https://github.com/chiel92/vim-autoformat#basic-definitions
Another option would be a PR to `vim-autoformat` itself, but not sure if can add filetype detection for snakemake files there.

**Comment by ashwinvis** [comment]
I use `neoformat` and I realized it is as simple as copying `black`'s definition. The only difference was there is no `-q / --quiet` flag in snakefmt, but it does not seem to matter. It works:
```vim
let g:black_linelength=82
let g:neoformat_snakemake_snakefmt = {
        \ 'exe': 'snakefmt',
        \ 'args': ['-l '.g:black_linelength, '-'],
        \ 'stdin': 1,
        \ }

let g:neoformat_enabled_snakemake = ['snakefmt']
```

To make it work I run `:Neoformat` in any open file buffer. If you want to mimic this in your plugin you could:

```vim
if exists(":Neoformat")
  command! Snakefmt :Neoformat! snakemake snakefmt
endif
```

Or contribute it upstream into the `neofrmat` repo.
