### ISSUE TITLE
Support snakefmt in github/super-linter

### ISSUE THREAD

**Issue by kpj** [snakemake/snakefmt#64]
To make automatic linting of `Snakefiles` using GitHub actions easier, I started a PR to add snakefmt to its supported linters: https://github.com/github/super-linter/pull/689

Hopefully this is something you also find useful :)

**Comment by bricoletc** [comment]
Great!
@kpj in that PR i might suggest not calling `snakefmt` a linter,but rather a formatter?
`snakemake --lint` at command-line provided support for snakemake code analysis, which i think could be a different check run by this github action

**Comment by kpj** [comment]
That's a good point, thanks for the feedback!

Is there a difference in what `snakefmt` and `snakemake --lint` can tell me about the quality of a `Snakefile`?
Does it make sense to include one over the other, or maybe both?

**Comment by bricoletc** [comment]
Depends what you want- snakefmt is for the code to 'look good', with no statements about how the workflow is written. It's to snakemake what `black` is to python; black won't tell you your function is too long, it'll just reformat it. `--lint` tells you about good practices, for eg recommending using `conda` and `log` inside `rule`s

**Comment by kpj** [comment]
It seems like both would be useful. I added support for `snakemake --lint` and `snakefmt` separately.

**Comment by bricoletc** [comment]
Ok :)

**Comment by mbhall88** [comment]
@kpj would you be able to put in a PR with a small section in the docs showing how people could use this in their workflows? A subsection in https://github.com/snakemake/snakefmt#install with the heading GitHub Actions

**Comment by kpj** [comment]
Yes, absolutely :)
I'll first try the setup with a few of my own repositories and then add the section.

**Comment by kpj** [comment]
I added a draft in #72.
