### ISSUE TITLE
Crash when running snakefmt 0.1.4

### ISSUE THREAD

**Issue by kpj** [snakemake/snakefmt#65]
I am using `snakefmt` v0.1.4 on macOS 10.15.6. When simply running the script, it crashes:
```bash
$ snakefmt
Traceback (most recent call last):
  File "/Python/3.8/bin/snakefmt", line 5, in <module>
    from snakefmt.snakefmt import main
  File "/Python/3.8/lib/python/site-packages/snakefmt/__init__.py", line 6, in <module>
    __version__ = toml.load(project_fpath)["tool"]["poetry"]["version"]
  File "/Python/3.8/lib/python/site-packages/toml/decoder.py", line 133, in load
    with io.open(_getpath(f), encoding='utf-8') as ffile:
FileNotFoundError: [Errno 2] No such file or directory: '/Python/3.8/lib/python/site-packages/pyproject.toml'
```

This seems to be due to the following two lines:
https://github.com/snakemake/snakefmt/blob/25c046b55c2df530a865485335fa170208772d7e/snakefmt/__init__.py#L5-L6

**Comment by mbhall88** [comment]
Yes, I'm also having this problem in https://github.com/bioconda/bioconda-recipes/pull/24238. @bricoletc I think we might need to change the way the version number is gathered back to what it was before?

**Comment by bricoletc** [comment]
Thanks for this @kpj , I should totally have looked into this when trying to have single version specification in pyproject.toml.
Problem is `pip install` does not distribute pyproject.toml. This was really handy to find a fix: https://github.com/python-poetry/poetry/issues/273
Running `poetry build` to distribute package creates PKG_INFO, pyproject.toml and setup.py files which all have the version from pyproject.toml. Then if you distribute sources and `pip install` you get a .dist-info directory which contains a METADATA file and that has version in it.

I added fix recommended in https://github.com/python-poetry/poetry/issues/273 by using `importlib.metadata.version`

I confirmed this works from both `pip install snakefmt` and `poetry install` from a local copy of the sources.

@mbhall88 i almost feel like we need to push this change to test pypi or something and `pip install` to confirm this works?

**Comment by bricoletc** [comment]
@mbhall88 `importlib.metadata` was only added to Python standard library in 3.8 so my proposed fix now uses a backport called `importlibs_metadata`. This adds a dependency to `snakefmt` but I quite like it, you can do a lot more package introspection than just getting the version

**Comment by bricoletc** [comment]
This seems to have worked, closing!
