### ISSUE TITLE
Use return code of `snakefmt --diff` to signal whether modifications are made

### ISSUE THREAD

**Issue by kpj** [snakemake/snakefmt#68]
`snakefmt --check` uses its return code to signal whether the source file needs changes. `snakefmt --diff` shows which changes are needed but does not signal its status using its return code. Using both parameters at the same time is not possible (`[WARNING] Both --check and --diff/--compact-diff given. Only running --check...`).

It would be great if `--diff` and `--compact-diff` would also set the return code to `0` if no changes are made and `1` instead. This would be useful e.g. in https://github.com/github/super-linter/pull/713.

**Comment by bricoletc** [comment]
Hi @kpj , i wonder why your super-linter action needs to run both diff and check?
A check exiting with exit code of 1 indicates changes would be made, without showing what changes; `--diff` shows those changes.

In an automated setup, is it not enough to signal that the file does not conform to `snakefmt` format using `--check` only?

+ @mbhall88 what do you think of adding an exit code to diff?

**Comment by mbhall88** [comment]
>    @mbhall88 what do you think of adding an exit code to diff?

Hmm, I am not keen to have diff give a non-zero exit code. In trying to keep inline with `black`, `black` does not return a non-zero exit code for its `--diff` option. It also seems misleading for `--diff` to give a non-zero exit code for "doing its job".

**Comment by kpj** [comment]
> In an automated setup, is it not enough to signal that the file does not conform to `snakefmt` format using `--check` only?

That would probably also be fine, although the other linters currently also show what needs to be changed.

> However, we probably should allow both `--check` and `--diff` at the same time. Would this solve the issue @kpj ?

That would be perfect! This is also how black is used at the moment.

**Comment by admiralAwkbar** [comment]
@mbhall88 I agree with @kpj that running the tool with both flags help show what can be corrected on the file and also exits with error code to signal to the user that the file needs to be updated. Allowing but would greatly help get this working again in the `Super-Linter`

**Comment by bricoletc** [comment]
Alright, lets work on this !

**Comment by kpj** [comment]
@mbhall88, @bricoletc: Should I create a PR which adds this feature, or what would be best for you?

**Comment by admiralAwkbar** [comment]
@mbhall88 Thank you for making the update to allow for the 2 flags to be run together!

Can we get a  `0.1.6` release so i can pull that in and update the `Super-Linter`? thanks!

**Comment by bricoletc** [comment]
It will come soon, we just need to test our changes a bit more :-)
