### ISSUE TITLE
provide an example of the formatting in the README

### ISSUE THREAD

**Issue by ctb** [snakemake/snakefmt#7]
it would be nice to be able to see an example of the formatting somewhere!

**Comment by mbhall88** [comment]
Hi @ctb ,

Agreed. As of yet, we do not actually have the formatting nailed down (still working through the nuances of parsing). This project is in an extremely new stage (we only started working on it a week and a half ago basically). But once we have some examples we will definitely update the README.

**Comment by ctb** [comment]
great! lmk if and how I can help.

**Comment by bricoletc** [comment]
WIP: https://github.com/mbhall88/snakefmt/wiki/Formatting-Guide

**Comment by bricoletc** [comment]
this is done !
