### ISSUE TITLE
Feature (doc?) request: vscode editor integration

### ISSUE THREAD

**Issue by austinkeller** [snakemake/snakefmt#80]
If possible, it'd be helpful to have steps in https://github.com/snakemake/snakefmt/blob/master/docs/editor_integration.md describing how to integrate with vscode

**Comment by austinkeller** [comment]
Ah, it looks like there's a plugin available: https://github.com/tfehlmann/vscode-snakefmt-provider

Maybe the docs could mention that?

**Comment by mbhall88** [comment]
I've never used that editor. But if you have set it up and feel the plugin is working well feel free to put in a PR here documenting how users can set it up, or at least pointing to instructions of how to do it.
