### ISSUE TITLE
ValueError: Unrecognised argument(s): force

### ISSUE THREAD

**Issue by Phlya** [snakemake/snakefmt#89]
Whenever I try to run snakefmt, I get this error:
```
$ snakefmt
ValueError: Unrecognised argument(s): force
```
This is all I get, and really not sure how to investigate
Version:
```
$ snakefmt --version
snakefmt, version 0.2.5
```

**Comment by bricoletc** [comment]
Hi @Phlya, let's look for more context here. 
What's your OS? And how did you install `snakefmt`?
Can you run `snakefmt -h` successfully?

**Comment by Phlya** [comment]
OS is Linux, on a cluster. Installed it using pip.
`snakefmt -h` works fine.

**Comment by Phlya** [comment]
I just tried reinstalling from conda, and get the same error.

**Comment by bricoletc** [comment]
Ah. I'm slightly at a loss, as I cannot reproduce the error, and can't see a place in the code where a `ValueError` is raised.

**Comment by Phlya** [comment]
Nope, I get the same error...
But I found the cause. I am using python 3.7, and `logging.basicConfig` argument `force` was only added in 3.8

**Comment by Phlya** [comment]
I'll try to update python in my environment, not specific reason I am still using 3.7 - but perhaps you might want to stay compatible with <3.8 and remove that argument.

**Comment by bricoletc** [comment]
That's a great catch @Phlya , thank you!! Definitely a bug, as we aim to support Python3.6.1 and above. Putting in a PR that fixes this.

**Comment by Phlya** [comment]
Awesome, thanks!
