### ISSUE TITLE
Error with nested else statement, InvalidPython

### ISSUE THREAD

**Issue by supermaxiste** [snakemake/snakefmt#96]
Hi,

I was trying to run a `--check` on my [Snakemake workflow](https://github.com/supermaxiste/ARPEGGIO) and I got a parsing error related to a nested `else` statement. This issue might be similar to #91.

For my `Snakefile` I get the following error:

```
[ERROR] In file "Snakefile":  'InvalidPython: Got error:
'''
Cannot parse: 1:0: else:
'''
while formatting code with black.'
```
This parsing error doesn't appear when I comment this `else` statement in my code:

```
if len(config) == 0:
	if os.path.isfile("./config.yaml"):
		configfile: "./config.yaml"
	#else:
		#sys.exit(f"Make sure there is a config.yaml file in {os.getcwd()} or specify one with the --configfile commandline parameter.")
```

**Comment by bricoletc** [comment]
Thanks @supermaxiste , this was indeed a bug, and I made a fix in branch `fix_96`. It now parses your Snakefile without error. We'll look to release a new version on PyPI soon, else you could try installing from source from branch `fix_96` and let us know if all OK!

**Comment by supermaxiste** [comment]
Hi @bricoletc,

just checked the branch and tried a run on my Snakefile, no parsing errors.

Thank you and feel free to close the issue anytime.
